### ISSUE TITLE
Hi,I want ask that did you use the Position Embedding Table in this project?

### ISSUE THREAD

**Issue by Keeplingshi** [ThanhChinhBK/event_detector#2]
I can't understand  how the  Position Embedding Table get in this paper.

**Comment by ThanhChinhBK** [comment]
hi, for example, with triger window:
[x<sub>i-k</sub>....x<sub>i</sub>...x<sub>i+k</sub>]
each x<sub>i+j</sub> is a concatenate of vectors:

- w<sub>i+j</sub>: word vector
- p<sub>j</sub> : postion embedding equivalent to j in postion embedding table
- e<sub>h</sub> : BIO entity embedding if you use
