### ISSUE TITLE
Data processing problem

### ISSUE THREAD

**Issue by superlyc** [ThanhChinhBK/event_detector#3]
Hi,

First, thank you for sharing the code. But I ran into this problem and not sure how did you handle it.

In file, 
/ace_2005_td_v7/data/English/bn/timex2norm/CNN_ENG_20030616_130059.25.sgm  

There is a "&" and resulted in Error: "xml.parsers.expat.ExpatError: not well-formed (invalid token): line 12, column 50", when excuting
doc = minidom.parse(text_path)

Thanks in advance if you could help

**Comment by DennisCraandijk** [comment]
I used the method described [here](https://stackoverflow.com/a/6121475) to change all `&` to `&amp;`
