### ISSUE TITLE
What's the meaning of "sub" in the data_script.py?

### ISSUE THREAD

**Issue by NotToday** [ThanhChinhBK/event_detector#6]
I'd like to write some code to deal with the data of other categories. However I don't understand the parameter "sub" in the "read_document" fuction. Could anybody tell me ? Thanks~

**Comment by NotToday** [comment]
Does it mean the number of space in the tags at the head of the ".sgm" file?

**Comment by NotToday** [comment]
Never mind, I rewrite it =。=

**Comment by xiaoya6666** [comment]
hello, have you solved the problem? what's the meaning of "sub"?
